package com.training.workout.model

enum class ExerciseName {
  EXERCISE_NAME_UNSPECIFIED,
  EXERCISE_NAME_PUSHUPS,
  EXERCISE_NAME_PULLUPS,
  EXERCISE_NAME_SQUATS,
  EXERCISE_NAME_PLANK,
  EXERCISE_NAME_RUNNING,
  EXERCISE_NAME_CYCLING
}